### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by marcomicera**
I've updated the main README file with the current instructions on how to launch Quartermaster, deleting references to the outdated guides on the website.

### CODE REVIEW

**Review by sebastian-su — DISMISSED** [review]
LGTM

**Comment by marcomicera** [comment]
Just noticed a pretty contorted sentence at the end of the main README file: fixed in e3b70b4.

**Review by lisa-noeth — APPROVED** [review]
In my understanding, "Results" should start when the graph is generated. The steps before seem like implementation steps. Otherwise, this looks good.

**Comment by marcomicera** [comment]
> In my understanding, "Results" should start when the graph is generated.

Agreed. I added the following:

> 1. Wait for the build and analysis phases to be over:
>
> ```bash
> kubectl logs --follow $(kubectl get pods --selector job-name=qmstr -o=name) qmstr-client
> ```

Under "[Results](https://github.com/endocode/qmstr/blob/k8s-readme/deploy/README.md#results)" as I wanna make sure that users retrieve results when they're ready.

> The steps before seem like implementation steps. Otherwise, this looks good.

So that would make it a "waiting step" that is necessary to retrieve results at the right time.
I admit that it's a bit forced.

Feel free to merge it if it's good enough.

**Comment by lisa-noeth** [comment]
Yes, that's fine.

**Pull request merged**
