### PR TITLE
fix build status badge in readme

### PR DESCRIPTION
**Pull request by sebastian-su**

### CODE REVIEW

**Comment by sebastian-su** [comment]
> The build status should be pointing to the master branch

true, I'll update that

**Comment by senaingrid** [comment]
@sebastian-su I can't merge it unless you mark the requested changes as done.

**Comment by GiasemiSh** [comment]
@sebastian-su Could you rebase to master branch instead of adding new commits?

**Comment by GiasemiSh** [comment]
> @sebastian-su I can't merge it unless you mark the requested changes as done.

@senaingrid We have the default behavior that we don't merge other's PR. The issuer of the PR should merge his/her PR, because the issuer may want to make a change before merging.

**Comment by sebastian-su** [comment]
ah I used the "update branch" button here which is obviously github style... since this is a simple change I'll redo the change in a new branch.

**Pull request closed without merging**
