### PR TITLE
Extensions for the validator concept

### PR DESCRIPTION
**Pull request by thegrumpylion**
* package = the metadata we have in our graph or read from a manifest (e.g. SPDX) representing a single package
* container = the "evelope" :/ that holds files (damn you container technology)
* manifest/metadata = produced by instrumented build or provided, consumed by validator

The manifest has at leat full path to file and a signature and can describe one or many packages.

The container is a flat file system. It has files that need validation and metadata. Containers can nest indefinitely as long as there are rules on what files are what so they don't count as files that are not described by the manifest -> fail. Each format specifies 2 methods. getFiles which should at leat return full path to file and a signature and getMeta that should parse whatever metadata files there is.

For example in the case of deb package it doesn't make sense to treat it as an ar container because the getFiles should return control.tar.gz and data.tar.gz and getMeta nothing.

A "distribution" or a collection container can be of 2 types. A flat file system that has each binary and conf files, etc. already at place (e.g. ubuntu-cloud-img) so the manifest has a list of packages with files that can be hashed at place or it can be a collection of nested package containers that may need to be handled recursively (a tar of dep packages??)

### CODE REVIEW

**Comment by thegrumpylion** [comment]
Btw, i couldn't add too much to the existing documentation. I played several scenarios in my head and it covers most if not all cases. What i see that may benefit from some extension is Development Plan that will become apparent after we discuss implementation details and agree on architecture.

**Comment by mirkoboehm** [comment]
Some good parts, some that seem to go in a different direction than the concept so far. A bit of this confusion is because of the use of the term distribution. Here are the definitions that are underlying to the original concept:
- A package is a concrete "form of archive" for distribution that is created during a build. It could be a tarball, a Debian or RPM package, or even a file system overlay that contains only what was packaged. For the first implementation, we want to focus specifically on Debian packages and then abstract the concept.
- A distribution is a collection of packages. The concept is not related to "Linux distribution", but to a typical software delivery.
- A manifest describes exactly one package. 
- The manifest for a distribution describes the content of the distribution (the package in the collection). The elements of the distribution contain or bring their own manifests.
- The validator validates one package, however "traversing into elements". That means it first validates that the distribution is "correct", and then validates that the same goes for all element packages.
- There should be no separate concepts for packages and distributions. Distributions are simply packages that contain other packages instead of files to be installed. Or - if you "install" a distribution file into a directory, you get the element packages.
- We will not use the dirty word "container' :-)

**Comment by thegrumpylion** [comment]
> * A package is a concrete "form of archive" for distribution that is created during a build. It could be a tarball, a Debian or RPM package, or even a file system overlay that contains only what was packaged. For the first implementation, we want to focus specifically on Debian packages and then abstract the concept.

Clear. Can we map this package to the QMSTR one and the SPDX one?

> * A distribution is a collection of packages. The concept is not related to "Linux distribution", but to a typical software delivery.

Agree but what is a "typical software delivery"?

> * A manifest describes exactly one package.

Clear

> * The manifest for a distribution describes the content of the distribution (the package in the collection). The elements of the distribution contain or bring their own manifests.

Clear

> * The validator validates one package, however "traversing into elements". That means it first validates that the distribution is "correct", and then validates that the same goes for all element packages.

Agree

> * There should be no separate concepts for packages and distributions. Distributions are simply packages that contain other packages instead of files to be installed. Or - if you "install" a distribution file into a directory, you get the element packages.

We are on the same page here.

> * We will not use the dirty word "container' :-)

I might tattoo this on my forearm

**Comment by mirkoboehm** [comment]
> ...
> Clear. Can we map this package to the QMSTR one and the SPDX one?

A package as a file is something meant to be "distributed" (abstract concept, placed outside of where it was built). A package node in QMSTR is a part of the database that describes a package. A SPDX file describes a package (which is a file or unit of distribution).

> > * A distribution is a collection of packages. The concept is not related to "Linux distribution", but to a typical software delivery.
> 
> Agree but what is a "typical software delivery"?

Not a technical but a business term: a software delivery is the handover and acceptance of a package (or set of packages, a distribution) from a supplier to a customer.

> > * A manifest describes exactly one package.
> 
> Clear
> 
> > * The manifest for a distribution describes the content of the distribution (the package in the collection). The elements of the distribution contain or bring their own manifests.
> 
> Clear
> 
> > * The validator validates one package, however "traversing into elements". That means it first validates that the distribution is "correct", and then validates that the same goes for all element packages.
> 
> Agree
> 
> > * There should be no separate concepts for packages and distributions. Distributions are simply packages that contain other packages instead of files to be installed. Or - if you "install" a distribution file into a directory, you get the element packages.
> 
> We are on the same page here.
> 
> > * We will not use the dirty word "container' :-)
> 
> I might tattoo this on my forearm

**Comment by mirkoboehm** [comment]
I am closing this PR because the results from the discussion have been incorporated in to the story in a separate PR.

**Pull request closed without merging**
